/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fcul_wrapper_Sloth */

#ifndef _Included_fcul_wrapper_Sloth
#define _Included_fcul_wrapper_Sloth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fcul_wrapper_Sloth
 * Method:    encode
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fcul_wrapper_Sloth_encode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     fcul_wrapper_Sloth
 * Method:    decode
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_fcul_wrapper_Sloth_decode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
