spring:
  threads:
    virtual:
      enabled: false

app:
  storagePath: ./nodes/${app.id}
  filesToPlotPath: ./nodes/files
  seedNodes:
    - "http://localhost:8080"
    - "http://localhost:8081"
    - "http://localhost:8082"
    - "http://localhost:8083"
